### PR TITLE
add versioning tag to latest docker image

### PR DESCRIPTION
**Pull request by traktuner**

### CODE REVIEW

**Comment by Inrixia** [comment]
Is there a reason behind why having additional tagging would be worth it?

Also if I was to merge this I would probably want to use the commit id rather than the run numbers.

**Comment by Inrixia** [comment]
Is there a reason behind why having additional tagging would be worth it?

Also if I was to merge this I would probably want to use the commit id rather than the run numbers.

**Comment by Inrixia** [comment]
Is there a reason behind why having additional tagging would be worth it?

Also if I was to merge this I would probably want to use the commit id rather than the run numbers.

**Comment by traktuner** [comment]
Hello 👋
Definetely. I work with a big Docker environment, and maintain image versions with [Renovate](https://github.com/renovatebot/renovate). It checks my repo (full of docker-compose files) and auto-commits new tags (if configured) to that repo.
Instead of $github.run_number you could use the long commit SHA as GITHUB_SHA and this would then be your tag.

**Comment by Inrixia** [comment]
Yes. Also apologies for the duplicate comments github is having a bit of a moment currently.

What's the reasoning behind tagging each commit, afik there isn't really a use case of people needing to target specific versions outside of dev and latest.

**Comment by Inrixia** [comment]
I don't mind the idea. I'm just wondering what practical use they offer.

**Comment by traktuner** [comment]
> I don't mind the idea. I'm just wondering what practical use they offer.

Maybe use the real version of the app for the docker tag? It's in the package.json and could be extracted via SED in the github-action that builds the docker images. That would be the best solution in my opinion.

**Comment by Inrixia** [comment]
Issue with that is that dev sometimes retains the latest release version as it is not automatically updated.

Using said version numbers would only be useful if people wanted to use older versions of the app. But that's generally a bad idea since most older versions aren't compatible with floatplane api changes.

I do agree about the versioning. I'm just struggling to come up with a use case outside of the one above that would justify the additional tagging.

**Comment by traktuner** [comment]
Since the dev images are built separately, the tagging that makes sense would be like dev + dev-5.7.0, and for latest only latest + 5.7.0.
But you are totally right, I didn't realize that the API changes make "outdated" versions useless most of the time. Don't want to overcomplicate things here...

**Comment by Inrixia** [comment]
Yea, honestly I may revisit this in the future if a genuine need for older versions becomes useful. But as it stands currently trying to use older versions will at best result in unexpected behavior.

Really appreciate the info though, I'll close these for now but can always come back to them down the line.

Thanks again

**Pull request closed without merging**
