### PR TITLE
Switch to current-alpine to slim down Docker builds

### PR DESCRIPTION
**Pull request by kprinssu**
This PR will change the base Docker images to use the latest Node version on top of the slimmed down Alpine images.

### CODE REVIEW

**Comment by Inrixia** [comment]
Why was this closed?

**Comment by kprinssu** [comment]
Apologies, I was making sure the container was functional and it is 🎉 !

**Comment by Inrixia** [comment]
What's the size difference of the image after these changes?

**Comment by kprinssu** [comment]
It's about 2/3 size of the normal images:

```
# docker image ls | grep floatplane
kprinssu/floatplane-downloader        dev             789116f7076c   27 hours ago        237MB
inrix/floatplane-downloader           dev             90340801283b   5 days ago          301MB
```

The base alpine images remove a lot of cruft.

**Comment by Inrixia** [comment]
Awesome thanks!

**Pull request merged**
