### PR TITLE
Partial pull request from Rob1998

### PR DESCRIPTION
**Pull request by DavidSpek**
I forked the main repository and added the docker files created by rob1998. The reason I did this is that the fork by rob1998 had issues with the float.js where it wanted to remove and replace each line. While a quick scan made it seem as if it would be the same, this way the docker file can be added without risking breaking the float.js.

### CODE REVIEW

**Comment by rob1998** [comment]
Looks good 😄 
I had some issues in the past, that's why I didn't do a pull request. But I've been running my docker stable for a few months now

**Comment by DavidSpek** [comment]
I've added a correction in the float.js to create the subChannel folders as I believe the subscription titles have changed for new subscribers.

**Comment by DavidSpek** [comment]
> Looks good 😄
> I had some issues in the past, that's why I didn't do a pull request. But I've been running my docker stable for a few months now
> 
> Edit:
> I don't have a lot of experience with building dockers, so if anyone sees something that can be improved, please improve it 😅

There seem to be a few anomalies in your template. But I could send the one I created so it can be added to the unraid CA directory. However, I thought it might be nice to have a UI for editing the settings and keeping track of the downloads.

**Comment by rob1998** [comment]
Oh I already had forgotten that my template was in my repo
I updated it to my current setup. 
But feel free to push yours to the unraid CA directory, I'm sure others will benefit from that as well

I didn't bother to convert every setting into a variable, I completely agree that a UI to manage the config would be nice. I only added the ones that were necessary for me.
As far as changing the names of existing files when the naming scheme gets changes, I think it would be a nice feature to have. But this is not an issue with the docker, it's just a missing feature of the downloader-script.

**Comment by DavidSpek** [comment]
> Oh I already had forgotten that my template was in my repo
> I updated it to my current setup.
> But feel free to push yours to the unraid CA directory, I'm sure others will benefit from that as well
> 
> I didn't bother to convert every setting into a variable, I completely agree that a UI to manage the config would be nice. I only added the ones that were necessary for me.
> As far as changing the names of existing files when the naming scheme gets changes, I think it would be a nice feature to have. But this is not an issue with the docker, it's just a missing feature of the downloader-script.

That would indeed be for the entire downloader. Just thinking out loud so people can follow :).

**Pull request merged**
