### PR TITLE
Add preference to download only captioned/uncaptioned videos

### PR DESCRIPTION
**Pull request by charliedavison**
I saw this had already been requested and is something I'd like to have the option for as well.

Not familiar at all with the FP API (or this project yet) so this might be a naive approach, but appears to work as intended.

### CODE REVIEW

**Comment by Inrixia** [comment]
This does work, though I think I'd rather implement it directly into the subchannels rather than have it as a seperate floatplane level setting since it's scoped to a specific channel rather than a site wide feature.

For now I'll leave this open though

**Comment by charliedavison** [comment]
@Inrixia I see, yeah that makes sense.

You're suggesting something like


```
{
  "title": "FP Exclusives",
  "skip": false,
  "captionVariants": {
    captioned: true,
    uncaptioned: true
  }
  "identifiers": [
     {
	"type": "channelId",
	"check": "6413623f5b12cca228a28e78"
     }
  ]
}, 
```

?

**Comment by Inrixia** [comment]
I was thinking having the ability to enforce and/or in the subchannel matchers and adding a titleStartsWith matcher. Since the captions functionality is basically just sub channel matching.

Currently there is no way to enforce and/or pairings in the matchers though so I need to think of the best way to approach it.

I'm tempted to replace thr matchers with a string that just gets interpreted into code. Probably the most flexible.

**Comment by Inrixia** [comment]
@charliedavison I'm closing this as its been implemented in https://github.com/Inrixia/Floatplane-Downloader/commit/dd92e3fddf7856bb1c058d79ae307468160dbc80. That commit will likely require resetting the subscriptions in your settings as the schema has changed.

Ill update the wiki to reflect the new changes when I get the time

**Comment by Inrixia** [comment]
If you run into issues with the changes please open a new issue. Feel free to continue this conversation here or message me on discord. Thanks for the help

**Pull request closed without merging**
