### PR TITLE
time + waittime

### PR DESCRIPTION
**Pull request by orthanc42**
add timestamp to output at end of run before waiting and change wait time to 15 minutes

### CODE REVIEW

**Comment by Inrixia** [comment]
What's the point of this?

**Comment by orthanc42** [comment]
> What's the point of this?

ease strain on floatplane servers a bit and make it so console output has a timestamp prior to waiting. so one can see how long until it cycles again.

`[19:44:32 GMT-0500 (Central Daylight Time)] Checking for new videos in 15 minutes...`

**Comment by Inrixia** [comment]
I can see the use of printing the timestamp. Though I'd like to use something that doesn't have the baggage of the timezone etc attached to it.

Using
```ts
date.toLocaleTimeString()
```

Would work.

**Comment by Inrixia** [comment]
As for increasing the delay,. The endpoint that is hit every 5min causes basically 0 load on floatplane, it's only the endpoints being used for downloading that do so increasing the time will have 0 affect.

If increasing the delay did then I would have already done so so you can revert the extra delay.

**Comment by Inrixia** [comment]
Oh lol woops I didn't notice how your doing the dates. You can just call toLocaleTimeString directly off a new date object. You also don't need to pass Date.now() into a new date constructor.

But I can sort that out at some point. Thanks for the contribution! Its much appreciated

**Pull request merged**
