### PR TITLE
make season/episode numbering for NFO files configurable

### PR DESCRIPTION
**Pull request by bengennaria**

### CODE REVIEW

**Review by Inrixia — CHANGES_REQUESTED** [review]
Instead of adding two more settings which just contain duplicate information I think it would be better to use regex to just pull out the season and episode strings from the existing format string.

Can you switch to doing this instead.

**Comment by bengennaria** [comment]
> Instead of adding two more settings which just contain duplicate information I think it would be better to use regex to just pull out the season and episode strings from the existing format string.
> 
> Can you switch to doing this instead.

I can try to do that, but with the filePathFormatting being completely customizable I don't have a fixed format I can base regex on to extract the season and episode. I'll have to assume that the end user isn't going to deviate from  ` - S(.+)E(.+) - ` or ` - (.+)x(.+) - `

**Comment by Inrixia** [comment]
Yea, if they aren't using plex formatting we can just assume that the meta no longer matters. Or you could check the values and if they are undefined default to the old behavior

**Review by Inrixia — APPROVED** [review]
Looks good. I might move the regex setup outside the function since it never changes and add some comments/handling if no matches are found.

Thanks for the help!

**Pull request merged**
